name: solution_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  go_router: ^11.0.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  introduction_slider: ^2.0.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  simple_circular_progress_bar: ^1.0.2
  video_player: ^2.8.2
  flutter_map: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    # --- opensans--
    - family: sf_heavy
      fonts:
        - asset: assets/fonts/SF-Rounded-Heavy.ttf

    - family: sf_bold
      fonts:
        - asset: assets/fonts/SF-Rounded-Bold.ttf

    - family: sf_medium
      fonts:
        - asset: assets/fonts/SF-Rounded-Medium.ttf

